IF NOT EXISTS (SELECT 1 FROM sys.schemas WHERE name = 'dbo')
BEGIN
    EXEC('CREATE SCHEMA dbo;');
END

IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'Baskets')
BEGIN
    CREATE TABLE dbo.Baskets (
        Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
        Data NVARCHAR(MAX) NOT NULL,
        CreatedAt DATETIME2 NOT NULL,
        ModifiedAt DATETIME2 NOT NULL
    );
END



